blank_issues_enabled: false
contact_links:
  - name: "\U0001F4AC Kotlin/JS Community Chat"
    url: https://kotlinlang.slack.com/archives/C0B8L3U69
    about: "Get in touch with the community, ask for help and talk about Kotlin/JS and dukat."
